SELECT 
    ACCT_ACCOUNT_ID, 
    ACCT_CUSTOMER_ID, 
    ACCT_CUSTOMER_NAME, 
    ACCT_IBAN, 
    ACCT_BNK_ID, 
    ACCT_BRNCH_ID, 
    ACCT_CNTRY_CD, 
    ACCT_TYPCD, 
    ACCT_SUB_TYPCD, 
    ACCT_TYPE_NAME, 
    ACCT_TYPE_DESCRIPTION, 
    ACCT_BALANCE, 
    ACCT_CURRENCY, 
    ACCT_CRT_DT, 
    ACCT_UPDT_DT, 
    ACCT_LOCKED FROM 
    OLS0002.ACCOUNT2;